export const NAVBAR_PARAMETERS = ({
  NAVBAR_EXPANDED_WIDTH: 230, 
  NAVBAR_SHRINKED_WIDTH: 100,
  DRAWER_EXPANDED_WIDTH: 230, 
  DRAWER_SHRINKED_WIDTH: 100
})

export const HTTP_STATUS = {
  OK: 200,
  UNAUTHORIZED: 403,
  UNAUTHENTICATED: 401,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
}

export default {
  NAVBAR_PARAMETERS,
  HTTP_STATUS
};